### ISSUE TITLE
Confused about constants in code

### ISSUE THREAD

**Issue by dacb** [BeckResearchLab/USP-inhibition#3]
Can you provide a comment or some other indication of the meaning of the two numbers on this line: https://github.com/BeckResearchLab/USP-inhibition/blob/master/scripts/driver.py#L61

**Comment by pearlphilip** [comment]
The two numbers link to two rows where the SMILES strings were faulty and contained unrecognizable characters. So, I decided to drop those rows

**Comment by dacb** [comment]
OK, Rahul and I are going to go through the code and flag all the lines with constants, etc. in preparation for generalizing the code.  Is it OK for us to use this issue to ask for clarifications?

**Comment by pearlphilip** [comment]
Of course.

**Comment by dacb** [comment]
Actually, we'll use a google doc linked to slack...
